package frames

var Dog = DefaultFrameType(DogFrames)

var DogFrames = []string{
	`
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMWMMMMMMNXXWMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKK0KXWWMMMMMWWWNNNXXKKKKKNWWWWKOk0XNNNNXKXNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKKXNXKOO0XNNNXXK000O00OkOkkO000KkddxOO00Ok0KKK0O0KXNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMN0KNWWWN0OO0KKK00O0OOkOOOOOkOO00OOOkkOOkOOkxkOOkkOO00KKKKKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKXNX00XKKXK0OO0000OOOkkOOOOkkkkOO000OOkkkkxxkkkkkxxxkO0KKKK00000XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKKK00K0OOOkxxkkOOOOOkkOOOkkxkOOkxxxkkkkxkkkO00OOxxxxxkO00K0O000kO0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKKOOkkkkkkkkkkOOOkO0OkkkkkkkkO0OxdooxxkxxkO00000OxxxxxkkO0XK0KKOkkOKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKOkxxxkkOOO0OOO0000KK0OkkkkkxxO0OkkkkkkOOOOkkkkkkkxxddxkO0XNK0KOkkkO0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWX0kxxxkkkOkkkkxkkOOOOO0OkkxkkxxxxkOO000OOO000OOOOkxxddxkOO0XK00K0kkkxxxO0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXXXKK0kxdxxxxxxkkkOkxdxkkkkkOOOkkkkkkxkkO00OOOOO00000OOkkkkOOO0KKK0XX0OOkkddddxOKNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK00OkxxxxdddxxxxxxkOOxdxxkkOO00000KK0OkkkOOOOOOO0KK0OOOOOOOOOOOO000KK000kxdooddxkO0XWWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOkxddxxddddddddxxxxkkkxxkkO00KXXK0KK0Okkk00000KKXK0000OkkkxkkkkOOO00KKK0OkxdoodxdxO0XNNWMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKOxoodxxxkkkkkxxxxxxxxxkkxxkOO0KXNX00K000OOOKKKKXXXKKK0OkkxxxkkkkOO00KKXXKK00OkkxxdxxkOKKXWMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXOdooddddxxxxkkkkkkkkxxxxxxxxkkO00KNX00K0OkkxxO0K00KK0K0OkkkkxxxxxkkkO000KXXXK0000OOOOkkO0KKKNWMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxddxxdddddddddddddxxxxxdddxdxxkkOKXXKKKOkkxddxdddxO0OOOOkkkkxxxxxxkkkkOOO0KXK0O00OkkOkOO0KK0KNWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxddoddddddoollccccclooooddddddxxk0XNNXK0OOOkxddooxOOOOOOkkkkkkkkxxxxxxkkOkO0K00OO0OkkkkO00OkO0XWMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOooodxxxdolcc:::;,,,,;:cloooooddxxOKNNNXKKK00OkddxOK00OOOOOOOOkkkkxxxkkkkkkOO00OOO0OkOOkO00OkkkkKWMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOolodxxxdolc;;,''......';clloooddxxkOKXXNNXXKOOOxk0KXK000OOOkkkkkkxxxxkkkkkkOOOOOOkO0OO0kk00OOOkkOXMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOoclodddollc:;'..      ..,:cllloddxkOOO0KKKKXX00OxOKXXK0OOkkkkkkxxxxxxxxxxkkkO000OOOO0OO0OkO00kOOkk0NWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxl::ldxdolc:;,'.         .';:ccloodk0KKKKK0OKXXXKOk0KK00OkxxxxxxxxxxxxxkkkkkkkO0KK0000OOOOOkk0000OkkOOKNMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMXkl:;:okOkxolcc:,.          ..,;:clloxOKXNNNX0kkkOKK00XK0OkkxddddddddddddddxxkkkkO000KK0K0OOOOOO0K00OOkOkk0XWMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMW0dc;;:lk00Okxddl:'           ..;::lodxkO0XXXNXKOkkk00KXNX0OOkddoooooollllllooddxkkkOOOKKKK000OkkOKK00OkkO0OO0KNWMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMXkl;,,,;lkOOkxxdoc'.   .        .:dddkOO0KKXXKXXKOOOkk0XNXK0Okxddooool::;;::ccloodxkOOOO0KKKKKKKOOKXK00OkkO000O00KNMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMW0o:;,;;:ldkkxdoolc,.   ...   ....,cxO00KK0KKKK00K0000OkOXNK0Okkxdooolc:;,,',,;:clodxkkkO0KKKKKKXX00KK0kkOkkOO00000k0NMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMNOc,,,,;::cldolcc:::;'.     .  .'cooodO0000000O000000KK0kkOK00Oxdoolllc:,..   ..';lodxkkkO0KKXXKKNNXK0K0kkOOOOO00000OkKWMMMMMMMMM
MMMMMMMMMMMMMMMMMMMW0d:,,,,;cc;:llc::::ccc:,'......,;codxxxOOOOO00OO0K0O0KXKK0kxxOOkxoolcc:;,..   ... .':lodxkO0KKXXNXXNNK0K0kkO0K0OOOkOOOO0NMMMMMMMMM
MMMMMMMMMMMMMMMMMMNkl:;,;;cddc;:cc::ccccllllc:,,;coooloddxkOOO0000O0KKK0KXNNNNKkxxkxxolc::;''... .,c:'  .:lodxxkO00XNXXNNK0K0kkO0000OkxxkOOOXWMMMMMMMM
MMMMMMMMMMMMMMMMWKxlc;,;cdkxc::::::cccloooollllloxkkxddoodxkkOO00OO0KKKKXNNNNNNK0kxxdolc:;,.''... .'''...,lodkO00K0KXXNNX00K0kkkOOO0OkxdxkO0KWMMMMMMMM
MMMMMMMMMMMMMMMNOolc:;;cxkdlc::;::::codxdoolclodxxkxxdddodxxkkkkkkO0KKKKXNNNWWNNX0kxddoc::;'.,'.......,,.':odxO00KXKKXNNX000OOOOOOO0OkxdxkO0XWMMMMMMMM
MMMMMWWNNNNWWW0dcc:::;cxdllcc;;;;;:ldxdooddddddddoodxxxddodxxkxdxkO0K00KXNWWWWWNXK0OOkxoc:;,''.....,:lc:;,;ldxO0KXXXXXNXK000Ok00OOO00kxxxkO0XWMMMMMMMM
WX0OOOkxxxxkkxolcc:;;;odlllc:,;;;:lddoodxkxxxxddoollodxxdoodxxxdxkO000KXNWWWWNNNXKK0OOxdoc:::;,,,,';locllllcodkO0XNNXXNK0O00OO00OO0K0kxxxkO0XWMMMMMMMM
Kkddxxxxxxxxxdddlc:;;:lcclc;;;,,:cooolodxxdoodddooooloddxdodxxxxxkO0KKXXXXNNNWWWNXK00OkxdolllcccccllloxkOOkdoodk0KXNNNXKOO0K0KK0O0000OkkxkO0XWMMMMMMMM
WNKOxddodddddxxxol:;;:::cc;:;;;;:cllodxxxdooooooooooooodddddxxxxkO00KKKKKXXXXXNNNXXK00OOkkxdddoooodxxkOKKK00kdodxOKNNXXKOO0KKKK000O0OOkkkO00KNWMMMMMMM
MMMWXOdodxddxxxxdoc;;,;cc;;::;;;:clodddooooooooooooooodddddxxxxkOO00KXXXXXXXNNNNNXXKKKK000OkxxxddxkO0KKKK000OOkdxxOXNNKOOk0KKK000OO0OOOOOO00KXNMMMMMMM
MMMMMNOdddxkkkkxxdl:;,:lc:c:;,,;:cllllllllloooooooooooddxxxxxkkO0KKXXXXXXXXXXXXNNNNXXXXKKK0OOkkxxkkO0KKKKK0OkkOOkkxOXNXOk0XX0K0O0000OOOOO0O0KKKXWMMMMM
MMMMMMNOdoxxxxkkxxdoc;:lccc:;;:cloooooooddddxxxxddooooodkkxxkO0KKXXXXXXXKKKKKKXXXXNNNXXKKKK000OkxkOOO00KKKK00OOOOkxxOKXK0KNX00K0O00OOOOOO000KK0KNMMMMM
MMMMMMMWKkkxxddddxxxolldxxxxxxxxxxxxxxxxxxxxxkOOOkxxdoldxkkO00KKKXXKKXXXXXXXXXKXXXXXXKKKKXKKKK0kxkOOOO0K00KK0000OxdxkO0KKKXX00KK0K00OOOOO000KK00XWMMMM
MMMMMMMMMWNX0xooooxkkxxkkkxddoooddddxkkkkkxxxxxkkkkkkdodxkOOOO0000OOOOOOOO0KKKXXNNXXXXKKKK000K0OkOOOOOKKK00KKK00OkddxkO0XXNXKKXXKKK000OOO0KKKKKKKWMMMM
MMMMMMMMMMMMWN0oldxxxxdddooolcclodxxkkkOkkkOOkkxxkkkkxddxxxdxxxxxxxkkkkkxxxxkO0KXXXXKKKKXKK00K000O00O0KXXK00KKKK0OxdxkO0XNNXKXNXKKK0000OOOKK0KKKKXWMMM
MMMMMMMMMMMMMMXxloooollllllllloooollllloodddxkO0OkkxxddolllooddddddxxkOOOOkxxkO0KKXXKKKKXXXXKK00000000KXXXKKXXKKKK0kxkOKNNNXXXNKKXKKK000OOKK0KKK00KNWM
MMMMMMMMMMMMMMWOl:c::cllllllllllcccc::ccloooooxkOOxdolcc:cloooooddxkkkkOOOOOkk000KKXXKKKKKKXXK0KK000KXXXXXXXXXK00KKKOO0XNNNXXXXKKXXKKK00OO0K00K00000XW
MMMMMMMMMMMMMMMNk:,;clllllccccccc:::::ccllooooooodxocc:::cllllloodxxkkkkkOOOO000000000000OOO0KKKK00KXXXXXXXXXXK0O0KKK0KXNNNNXXXKKXXKKK0000KKKKKK000OO0
MMMMMMMMMMMMMMMMNd;:cllllllccc::::::;::ccc:::cllllcc;,,;;:clooodddddddddddxxxxkkkOOO000000OOOO0KK0KXXXNXXKXXXKKKOk0KK0KXNNNXXKXKKKKKKKKK0KKKKK00KKK0Ok
MMMMMMMMMMMMMMMMW0oclooolcccc::::;;;;;;;;;,,,;:cc:,''''',;;clllodddoollooodddddddxkO0000000OOOO0KKKKXNNNK0O0KKKKOxkKK0KXNNNXK0KKKKXXXKKKKKKKKK00KXK0OO
MMMMMMMMMMMMMMMMMXocooolccc::::;;;,,,,'......'','.......',;;::coddoollllooddxxkkkxxkkO0000OOkkO0KKKKKXNNX0xx0KKK0xx00KXNNNXXK0000KXKXK0KKKKKKK0KKKKOO0
MMMMMMMMMMMMMMMMMXdloolccc::::;;,,''.....................',;;;::clodooooooddddxkkkkkkkOOO0OOOOO0KKK00KXNXKkdxO000xx00KNNNXXXK00OO0KKK0O0KKKKKK0KXK0XNW
MMMMMMMMMMMMMMMMWKdoolcccccc::;;,''..................''.'',;;;::::loooodxdooddddxxkkkOO00OOOO000KK0000KXXKkddxO0OxkO0XXNXKKKK00OOO0KXKOOKKKKKKKKXXNWMM
MMMMMMMMMMMMMMMMNkollllcccc::;;,,''..    ......''..'''''''',,;;::;:ccccldxxddddddxxxkkOO000OO0K0KXK0000000kdodkOkxxk0NNXXK00000OOO0KXK00K0KKK0KKXWMMMM
MMMMMMMMMMMMMMMMKdllllcc:::;;;,,''..       ........',;;,'''''',;;,;cccllodxxxddxxxxxxkkkO0K0O0KKKKK00O00OOkoodkkxxdkKNNNX00OOO0OOO0KK00K000KK0KXWMMMMM
MMMMMMMMMMMMMMMM0ocllcc:::;;;,,''..          .......';::;,''''',,',::loooddxxxxkkkkkkkkkOO0000KKKXNK0OOOOOxlldxxlcdOKNNXK0OkkO00OO0KKKKKOO0K0KNWMMMMMM
MMMMMMMMMMMMMMMMKoccccc::;;;,,,''..                ......'''''.'''',:loddddddxxkkOOOkkkkOO0000KKKNWXOOOOOkdcldo:,;oOKXXXK0kxkOK0O00KKXX0kkO0KNMMMMMMMM
MMMMMMMMMMMMMMMMXdccc:::;;;,,,,''..                        ......',:loddxxdddddxxkOOOOOkkkO0000KKNNKOOOOkxlcol;'';oOKXXK00kkk0K000KKKKX0Ok0XWMMMMMMMMM
MMMMMMMMMMMMMMMMXdcc::;;;,,,,,''''..                          ...,:clodxxkkxxxxxddxOOOOkkxxkOO0KKXNKOkkkxo:::,'',;oOXXK0KOkkO00000KK0OK00XWMMMMMMMMMMM
MMMMMMMMMMMMMMMMXdcc:;;;,,,,,,''''..                .         ..,:lloodxxkOOOkkxxddxkOkkkxddxkOK00K0Okkxd:,,''''';oOKK00KOkxkOO00000OkOKNMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMNkc:;;;,,,,,''''''...              ...'........':lllloddxkkkOOOOkkxddxkkOkddxxk0OOOOkkxdc;,,,''',:ok00000OkxkkkO0OxxkkONWMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMW0l;,;,;;,,''''''....                   ......,::clllodxxkkkkOOOOOkxxxxxkkddxdxkkkkkkxdc,'','',;cclxO0K00kxxxxkkOkolokKWMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMNx:;;;;;,',''''.......                   ..,:c:::cllodxxxxxkkkkkOOkxddoddxxxddxxxxxxdl,..',;;codlcd0K00OkxkkkkkOkoco0WMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMXo:;;::,',''''.........               ..,;;::;::ccloodddddxxxxxxkkxollloxxdoddddxxol:'.',:codkOd:lkOOOOO000OkOOkxoxXMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMW0l;:::,,''''''.....              .....'''',;;::lllccloooooddooodxdlcccodxoooloddo:;;,,:loxkO0OklcdkOOO0K0OOOOOkkdkXMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMWOc::;,''''',,'....               ........,;;::clolc::cclllollllodlccclddollclooc:;;:ldxkOO0000koddxk0K0OOOOOOOkxkXMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMNx:;;,''''','....                       .',,;:::cc:::;;;:ccc:cclolcccloolc::lol::cldk0O0000OOO000OOOKK00OOOOOOOkkKWMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMXd:;,''.........  ..........            ...';;;;;;;;;;,,;:c::ccllcccclol:;coooooodx0KOO0OOOOOO0KXXXXKK00OO000OOOKNMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMXd;,'..........   .............         ....'',,,,',,,,,;:::::cllcccclc:codddddddOK0OOOOOOOOOO00KKKKXX0OO0K00OkOXMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMXxl:,,'........  ..............          .....'',''''''',,;;:clccclllloxkkxxxxkO000OOOOOOOO00000KKKXK0O00K000OxOWMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMWNXK0kxooc:,'....................        .......'''''''',,;:ccccodxk00000000OOOOOOOkkOOOOOO0000KKXK000000000OxkXMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNKOd:...........................'',,..''..',,;c::cllldOKXXXXXXXNXXKK0OkxxxkOOOOO0000KXXNXK0000KKKKKkkXMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd:'.....................'',;;:cc;,;;;:c:collloddk0KKKK00KKKXXXKOxdddxkkOOOO0KKKXNNNXKKKKKXXXK0xxXMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOxl:;,,''''''''......,;;,;:oxxoccdkkxollllcoddxkO0KK0OO00KXX0kxdddxkkkkO00KXXXXKXKKKKKKXXKK0kkKMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXK0xl;;;,,',''..':ll::ldxkxlok0KKOxddollloxkkO0KKKK000KK0OkxdxxkkkOO0KKXNNXKKKXXXXXXKKK0Ox0WMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXd:;;;;,,,'';lddoodxkkolokO0KKKOkkkxddxxxkO0KNXKKK0OkkkkxkkkO000KXXXNNNXXKKXXXXXXXXKOxKWMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKdc:;;,;;::clooooddoolooxkkO0OxdkOkkkkkxxkOKKKK0OkkxxxxkkkOO00KXXXXNXXKKKKKXXXXXNXKOxKMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd:;,',;;cllooollccllodkkkkxoloxxxkOOkxxxkOO00OkxxxxxxxxkOO0KKXXXNXXKKKKKKKXXXXXXKkx0MMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkc,'..,:loddoc::;coxkkkkxollodooxOOOxxkkO00OkxxxxxxxxkkO0KKXXXXKK00000KK0KKXXXXK0k0WMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd;..';clol:;;;;:coxxxxdloxxxdodxOOkkOO0OkxxxxdddxxkO0KXXKK00OOOO00000KKKKKKKKKkxKMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOl:,;cllc:;;;;;:codddlldkkkxdoxOOkxkkkxddddddddxxkO0KKK00OkkO0000000KKKKKKXKOdxXMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo;,:cll:;,,;;:cloolcldkOkxookOOOkkkkkxdddxxxxxkOOO00OkkkOO000000000KKXXXX0OxONMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOxxdolc:;,;;:cllllccoxkxoloxkkkOOOOOOkxxxkkkO0K0000kkkkO000O000OO00KKKK0OxONMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNK0Odc:;,:clloolc:loddolloddxxxkkkOOkxkOOOOKK000OkOkkkOkOkOO0000KKXKK0kkXMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOo;,;clodxdlcclllllllodxxxxkkkOOOkO00000000kkkkxxkkxkkO0KK00KXXKOx0WMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxolloddxdlccllccllloodxxxkkkkkkkkOOOkO0OkkkxxxxkkkkO00KKKKKXX0xkXMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNK0kxddlcllllllooodxxxxxxxxxdddxkxxkkkkO0OOkO00OOO0000KKKKKOx0WMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKOkocclloooooddxkkkxdooooodxxdxkkkkOOOO000000000KKXXXXOdONMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWKkdooddooddxxxkkkxdoooooooodxkkkOOOkOOOO00000KXNNNN0x0MMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOOkkkkxdddxxxxxdooollooddxkOOOOOOOO00KXXXXXXXNXKkONMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNNXX0OxdddxxdoolloooddxkOOOOO000KXXNNNNXXXXXKOkKMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0kxddooooodddxkO000000KKKXXXXXNXXXXXK0kONMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKOxddddxxxkOKK0KKXXXXKKKKKXXNNNNXKOxkNMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOkkkOOOO0000KXNXXKKKKKXXNNNNXKkdOWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNK00OOOOO000KXXKK00KXXNNNXX0OxxXMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNXK0OOOO0KKXXXXXNWWNXX0kdoOWMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNXXKKKKKXNNWWNNXKOocdXMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0OKXXXNNNXOdlkNMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK00KKKXXKdoONMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0k0KK0Oxd0WMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkOXXOolxNMMMMMMMMMMMMMMMMMMMMMMM
 
  `,
}
